### ISSUE TITLE
Model Optimize unable to get Tensorflow version

### ISSUE THREAD

**Issue by somyamohanty** [tensorflow/model-optimization#448]
**Describe the bug**
Optimization package is unable to get the tensorflow version within the code while importing the module.

`import tensorflow_model_optimization as tfmot`

```
if (distutils.version.LooseVersion(tf.version.VERSION) <
     66       distutils.version.LooseVersion(required_tensorflow_version)):
     67     raise ImportError(

AttributeError: 'module' object has no attribute 'version'
```

**System information**

TensorFlow version (installed from source or binary): 1.8

TensorFlow Model Optimization version (installed from source or binary): 0.3.0

Python version: 2.7

**Describe the expected behavior**
should it be `tf.__version__` instead of `tf.version`
**Describe the current behavior**

**Code to reproduce the issue**
`import tensorflow_model_optimization as tfmot`

**Screenshots**
![Screen Shot 2020-07-01 at 10 09 58 AM](https://user-images.githubusercontent.com/2720456/86255576-41f76c00-bb85-11ea-8d77-8d0f9fead2ad.png)

**Comment by teijeong** [comment]
MOT toolkit needs TensorFlow version at least 1.14, so it won't work with TF 1.8 anyway. Closing this
